version: '3.5'

volumes:
  mongodb_rgcsm:
services:
  mongodb:
    restart: always
    image: mongo:4
    ports:
      - 27017:27017
    networks:
      - future-it-network
    volumes:
      - mongodb_rgcsm:/var/lib/mongodb
    logging:
      driver: 'json-file'
      options:
        max-size: '10k'
  backend:
    restart: always
    image: futureit_academy/node-web-app:latest
    environment:
      DB_URL: mongodb://mongodb:27017/admin
    ports:
      - 8080:8080
    networks:
      - future-it-network
    depends_on:
      - mongodb
networks:
  future-it-network:
    driver: bridge

