version: '3.5'

volumes:
  mongodb_rgcsm:
services:
  mongodb:
    restart: always
    image: mongo:4
    ports:
      - 27017:27017
    networks:
      - future-it-network
    volumes:
      - /home/ubuntu/mongodb:/var/lib/mongodb
    logging:
      driver: 'json-file'
      options:
        max-size: '10k'
  backend:
    restart: always
    image: ghcr.io/infy11/futureit_academy:latest
    environment:
      DB_URL: mongodb://mongodb:27017/admin
    volumes:
      - /home/ubuntu/photos:/usr/src/app/public
    ports:
      - 8080:8080
    networks:
      - future-it-network
    depends_on:
      - mongodb
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/caddy/Caddyfile:/etc/caddy
      - /data/caddy/data:/data # Optional
      - /data/caddy/config:/config # Optional
    networks:
      - web
      - future-it-network
networks:
  web:
    external: true
  future-it-network:
    external: false    
    driver: bridge


