name: Backup mongo db and images
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying services
        uses: appleboy/ssh-action@master
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          envs: CR_PAT
          debug: true
          script: |
            echo $CR_PAT |  docker login ghcr.io -u infy11 --password-stdin
            docker exec -d ubuntu_mongodb_1  mongodump
            docker cp ubuntu_mongodb_1:/dump .
            - name: copy file via ssh password
        - name: bringing backup to github runner    
          uses: appleboy/scp-action@v0.1.4
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            port: ${{ secrets.PORT }}
            source: ${{ secrets.HOST }}/dump
            target: /
